name: HardCoded Secrets

on: [push]

env:
  API_KEY: my_secret_key
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: super_secret_password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a command
      run: echo 'my_secret_key'
      env:
        TOKEN: another_secret_token
